Repository DeveloperAcademy-POSTECH/MC2-Team13-RnB, pull requests merged in 2022-06, with the labels that each got.

#6 [docs] #5 : Create New Project
  CleanFish/CleanFish.xcodeproj/project.pbxproj
  CleanFish/CleanFish.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  CleanFish/CleanFish.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  CleanFish/CleanFish/Assets.xcassets/AccentColor.colorset/Contents.json
  CleanFish/CleanFish/Assets.xcassets/AppIcon.appiconset/Contents.json
  CleanFish/CleanFish/Assets.xcassets/Contents.json
  CleanFish/CleanFish/CleanFishApp.swift
  CleanFish/CleanFish/ContentView.swift
  CleanFish/CleanFish/Preview Content/Preview Assets.xcassets/Contents.json
Labels: documentation

#27 [feat] : 선택한 생선과 선택한 손질이 담길 Model 정의하기
  CleanFish/CleanFish.xcodeproj/project.pbxproj
  CleanFish/CleanFish/Fish.swift
  CleanFish/CleanFish/Recipe.swift
Labels: feat

#32 [feat] #8 : 손질단계 중 Tabview로 Paging이 되도록 템플릿구현
  CleanFish/CleanFish.xcodeproj/project.pbxproj
  CleanFish/CleanFish/StagePagingView.swift
Labels: feat

#33 [feat] #9 손질단계화면 미디어 들어갈 7:5 View 자리 확보하기
  CleanFish/CleanFish.xcodeproj/project.pbxproj
  CleanFish/CleanFish/StageLayout75View.swift
Labels: feat

#34 [feat] #13 : 손질단계에서의 텍스트(제목,본문) 배치
  CleanFish/CleanFish.xcodeproj/project.pbxproj
  CleanFish/CleanFish/StageLayout75View.swift
Labels: feat

#35 [feat] #22 : 손질단계화면 홈버튼 생성
  CleanFish/CleanFish.xcodeproj/project.pbxproj
  CleanFish/CleanFish/ColorExtension.swift
  CleanFish/CleanFish/Colors.xcassets/Contents.json
  CleanFish/CleanFish/Colors.xcassets/homeBlue.colorset/Contents.json
  CleanFish/CleanFish/StageLayout75View.swift
Labels: feat

#39 [feat] #38 : Add Firebase SDK
  CleanFish/CleanFish.xcodeproj/project.pbxproj
  CleanFish/CleanFish.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CleanFish/CleanFish/GoogleService-Info.plist
Labels: feat

#48 [feat] #20 : 생선손질 안내문구 뷰 만들기
  .github/ISSUE_TEMPLATE/bug-issue.md
  .github/ISSUE_TEMPLATE/question-issue.md
  CleanFish/CleanFish.xcodeproj/project.pbxproj
  CleanFish/CleanFish/Assets.xcassets/HighlightColor.colorset/Contents.json
  CleanFish/CleanFish/Assets.xcassets/Image.imageset/Contents.json
  CleanFish/CleanFish/Assets.xcassets/ManColor.colorset/Contents.json
  CleanFish/CleanFish/Assets.xcassets/StartButton.colorset/Contents.json
  CleanFish/CleanFish/Assets.xcassets/rumor.imageset/Contents.json
  CleanFish/CleanFish/Assets.xcassets/rumor.imageset/rumor.png
  CleanFish/CleanFish/ContentView.swift
  CleanFish/CleanFish/Info.plist
  CleanFish/CleanFish/StageLayout75View.swift
  CleanFish/CleanFish/TutorialView.swift
Labels: feat

#51 [feat] #31 : 손질단계화면에서 홈으로 버튼 터치 시 가로모드로 전환하는 기능 추가
  CleanFish/CleanFish/StageLayout75View.swift
Labels: feat

#53 [feat] #52 : URLSession Manager 만들기
  CleanFish/CleanFish.xcodeproj/project.pbxproj
  CleanFish/CleanFish/Fish.swift
  CleanFish/CleanFish/MainView.swift
  CleanFish/CleanFish/NetworkManager.swift
  CleanFish/CleanFish/Recipe.swift
  CleanFish/CleanFish/SelectFishView.swift
  CleanFish/CleanFish/SelectRecipeView.swift
Labels: feat

#54 [feat] #40, #61 : Color Asset 생성
  CleanFish/CleanFish.xcodeproj/project.pbxproj
  CleanFish/CleanFish/Color+Extension.swift
  CleanFish/CleanFish/ColorExtension.swift
  CleanFish/CleanFish/Colors.xcassets/backgroundGray.colorset/Contents.json
  CleanFish/CleanFish/Colors.xcassets/primaryBlue.colorset/Contents.json
  CleanFish/CleanFish/Colors.xcassets/secondaryBlue.colorset/Contents.json
  CleanFish/CleanFish/Colors.xcassets/textGray.colorset/Contents.json
Labels: feat

#63 [feat] #62 : Image Asset 생성
  CleanFish/CleanFish.xcodeproj/project.pbxproj
  CleanFish/CleanFish/Assets.xcassets/Dish.imageset/Contents.json
  CleanFish/CleanFish/Assets.xcassets/Dish.imageset/Dish.png
  CleanFish/CleanFish/Images.xcassets/Contents.json
  CleanFish/CleanFish/Images.xcassets/boiled.imageset/Contents.json
  CleanFish/CleanFish/Images.xcassets/boiled.imageset/boiled.png
  CleanFish/CleanFish/Images.xcassets/dish.imageset/Contents.json
  CleanFish/CleanFish/Images.xcassets/dish.imageset/dish.png
  CleanFish/CleanFish/Images.xcassets/roast.imageset/Contents.json
  CleanFish/CleanFish/Images.xcassets/roast.imageset/roast.png
  CleanFish/CleanFish/Images.xcassets/sashimi.imageset/Contents.json
  CleanFish/CleanFish/Images.xcassets/sashimi.imageset/sashimi.png
  CleanFish/CleanFish/Images.xcassets/staticwave.imageset/Contents.json
  CleanFish/CleanFish/Images.xcassets/staticwave.imageset/staticwave.png
  CleanFish/CleanFish/SelectRecipeView.swift
Labels: feat

#68 Complete Merge
  CleanFish/CleanFish.xcodeproj/project.pbxproj
  CleanFish/CleanFish.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CleanFish/CleanFish/Assets/Images.xcassets/Contents.json
  CleanFish/CleanFish/Assets/Images.xcassets/boiled.imageset/Contents.json
  CleanFish/CleanFish/Assets/Images.xcassets/boiled.imageset/boiled.png
  CleanFish/CleanFish/Assets/Images.xcassets/dish.imageset/Contents.json
  CleanFish/CleanFish/Assets/Images.xcassets/dish.imageset/dish.png
  CleanFish/CleanFish/Assets/Images.xcassets/roast.imageset/Contents.json
  CleanFish/CleanFish/Assets/Images.xcassets/roast.imageset/roast.png
  CleanFish/CleanFish/Assets/Images.xcassets/sashimi.imageset/Contents.json
  CleanFish/CleanFish/Assets/Images.xcassets/sashimi.imageset/sashimi.png
  CleanFish/CleanFish/Assets/Images.xcassets/staticwave.imageset/Contents.json
  CleanFish/CleanFish/Assets/Images.xcassets/staticwave.imageset/staticwave.png
Labels: feat

#64 [feat] #55 : 손질단계화면에서 홈버튼 누를 경우 생선선택하는 화면으로 이동
  CleanFish/CleanFish/SelectRecipeView.swift
  CleanFish/CleanFish/StageLayout75View.swift
Labels: feat

#69 [feat] #47 : 시작하기 버튼 터치 시, 음성 인식 권한 받기, 마이크 권한 받기
  CleanFish/CleanFish.xcodeproj/project.pbxproj
  CleanFish/CleanFish/SelectRecipeView.swift
  CleanFish/CleanFish/StageLayout75View.swift
  CleanFish/CleanFish/TutorialView.swift
Labels: feat

#76 [feat] Lottie 적용
  CleanFish/CleanFish.xcodeproj/project.pbxproj
  CleanFish/CleanFish/App/CleanFishApp.swift
  CleanFish/CleanFish/Assets/Images.xcassets/boiled.imageset/Contents.json
  CleanFish/CleanFish/Assets/Images.xcassets/flatfish_grilled.imageset/Contents.json
  CleanFish/CleanFish/Assets/Images.xcassets/flatfish_grilled.imageset/roast.png
  CleanFish/CleanFish/Assets/Images.xcassets/flatfish_sashimi.imageset/Contents.json
  CleanFish/CleanFish/Assets/Images.xcassets/flatfish_sashimi.imageset/sashimi.png
  CleanFish/CleanFish/Assets/Images.xcassets/flatfish_stewed.imageset/Contents.json
  CleanFish/CleanFish/Assets/Images.xcassets/flatfish_stewed.imageset/boiled.png
  CleanFish/CleanFish/Assets/Images.xcassets/roast.imageset/Contents.json
  CleanFish/CleanFish/Assets/Images.xcassets/sashimi.imageset/Contents.json
  CleanFish/CleanFish/Assets/flatfish.json
  CleanFish/CleanFish/Assets/mackerel.json
  CleanFish/CleanFish/Assets/swipe.gif
  CleanFish/CleanFish/Assets/voicecontrol.gif
  CleanFish/CleanFish/Extension/Color+Extension.swift
  CleanFish/CleanFish/GIFView.swift
  CleanFish/CleanFish/LottieView.swift
  CleanFish/CleanFish/MainView.swift
  CleanFish/CleanFish/Manager/NetworkManager.swift
  CleanFish/CleanFish/Manager/PermissionManager.swift
  CleanFish/CleanFish/Model/Fish.swift
  CleanFish/CleanFish/Model/RecipeVO.swift
  CleanFish/CleanFish/SelectFishView.swift
  CleanFish/CleanFish/SelectRecipeView.swift
  CleanFish/CleanFish/StageLayout75View.swift
  CleanFish/CleanFish/StagePagingView.swift
  CleanFish/CleanFish/SwipeGuideView.swift
  CleanFish/CleanFish/TutorialView.swift
  CleanFish/CleanFish/VoiceGuideView.swift
Labels: feat, fix

#80 [feat] #78, #79, #66 : “마이크 심볼을 클릭했을때 설정으로 이동시키기, 권한 상태에 따라 바뀌는 마이크 심볼 …
  CleanFish/CleanFish.xcodeproj/project.pbxproj
  CleanFish/CleanFish/Manager/PermissionManager.swift
  CleanFish/CleanFish/StagePagingView.swift
  CleanFish/CleanFish/SwipeGuideView.swift
  CleanFish/CleanFish/VoiceGuideView.swift
Labels: feat

#83 [fix] #72, #82 : 메인화면~안내페이지 UI 수정
  CleanFish/CleanFish/Colors.xcassets/textGray.colorset/Contents.json
  CleanFish/CleanFish/SelectFishView.swift
  CleanFish/CleanFish/SelectRecipeView.swift
  CleanFish/CleanFish/SwipeGuideView.swift
  CleanFish/CleanFish/VoiceGuideView.swift
Labels: fix
